%% electron_tof_analysis.m
% Analisi TOF–path per gli elettroni, integrata nel progetto Trajectories.
%
% Usa:
%   - data_raw/trajectories/manual.txt   (output SIMION)
%   - simion.importSimionTofTable
%   - simion.analyzeTofPathCorrelation  (2 struct: stats_Lmin, stats_det)
%
% Scrive:
%   - data_processed/tof/electrons/electron_tof_path_stats.mat
%   - data_processed/tof/electrons/electron_tof_path_stats_summary.csv
%   - data_processed/tof/electrons/electron_tof_path_stats_summary.tex
%   - figures/tof/electrons/Scatter_TOF_Path_*.{fig,png}
%   - figures/tof/electrons/TOF_and_Path_histogram_*.{fig,png}

clear; clc; close all;

%% 1) Root del progetto e cartelle

scriptsDir = fileparts(mfilename('fullpath'));      % .../Trajectories/matlab/scripts
projRoot   = fileparts(fileparts(scriptsDir));      % .../Trajectories

% File raw (stesso manual.txt usato per l'analisi al detector)
rawTrajDir = fullfile(projRoot, 'data_raw', 'trajectories');
inputFile  = fullfile(rawTrajDir, 'electron.txt');

% Cartelle di output per l'analisi TOF degli elettroni
tofProcDir = fullfile(projRoot, 'data_processed', 'tof', 'electrons');
figDir     = fullfile(projRoot, 'figures',        'tof', 'electrons');

if ~exist(tofProcDir, 'dir'), mkdir(tofProcDir); end
if ~exist(figDir,     'dir'), mkdir(figDir);     end

if ~isfile(inputFile)
    error('File TOF elettroni non trovato:\n  %s', inputFile);
end

fprintf('>>> Analisi electron TOF da: %s\n', inputFile);

%% 2) Import SIMION -> table

T = simion.importSimionTofTable(inputFile);

%% 3) Analisi TOF–path (due scenari: solo Lmin, e Lmin+Xmax)

Lmin = 0;          % puoi cambiarlo se vuoi escludere cammini ridicolmente corti
[stats_Lmin, stats_det] = simion.analyzeTofPathCorrelation(T, Lmin);

%% 4) Salvo risultati numerici in .mat

matFile = fullfile(tofProcDir, 'electron_tof_path_stats.mat');
save(matFile, 'stats_Lmin', 'stats_det');
fprintf('    -> Salvato stats in: %s\n', matFile);

%% 5) Salvo le figure prodotte (scatter + istogrammi)
% La funzione analyzeTofPathCorrelation apre 4 figure:
%   1-2: scatter+hist per scenario Lmin
%   3-4: scatter+hist per scenario detector

figs = findall(0, 'Type', 'figure');
[~, idx] = sort([figs.Number]);
figs = figs(idx);

for k = 1:numel(figs)
    fname_base = sprintf('TOF_Path_fig_%d', k);
    saveas(figs(k), fullfile(figDir, fname_base + ".png"));
    saveas(figs(k), fullfile(figDir, fname_base + ".fig"));
end

fprintf('    -> Figure salvate in: %s\n', figDir);

%% 6) Costruisco una tabella riassuntiva e la salvo in CSV + LaTeX

Scenario          = ["Lmin_only"; "Detector"];
slope             = [stats_Lmin.slope;           stats_det.slope];
intercept         = [stats_Lmin.intercept;       stats_det.intercept];
R                 = [stats_Lmin.R;               stats_det.R];
R2                = [stats_Lmin.R2;              stats_det.R2];
FWHM_TOF          = [stats_Lmin.FWHM_TOF;        stats_det.FWHM_TOF];
FWHM_L            = [stats_Lmin.FWHM_L;          stats_det.FWHM_L];
FWHM_TOF_geom     = [stats_Lmin.FWHM_TOF_geom;   stats_det.FWHM_TOF_geom];
geom_fraction     = [stats_Lmin.geom_fraction;   stats_det.geom_fraction];
N_used            = [stats_Lmin.N_used;          stats_det.N_used];

Summary = table(Scenario, slope, intercept, R, R2, ...
                FWHM_TOF, FWHM_L, FWHM_TOF_geom, geom_fraction, N_used);

% --- CSV ---
csvFile = fullfile(tofProcDir, 'electron_tof_path_stats_summary.csv');
writetable(Summary, csvFile);
fprintf('    -> Tabella riassuntiva CSV in: %s\n', csvFile);

% --- LaTeX ---
texFile = fullfile(tofProcDir, 'electron_tof_path_stats_summary.tex');
fid = fopen(texFile, 'w');
if fid == -1
    warning('Non riesco ad aprire il file LaTeX per scrittura: %s', texFile);
else
    fprintf(fid, '%% Auto-generated by electron_tof_analysis.m\n');
    fprintf(fid, '\\begin{table}[ht]\n\\centering\n');
    fprintf(fid, '\\begin{tabular}{lrrrrrrrrr}\n');
    fprintf(fid, 'Scenario & $a$ & $b$ & $R$ & $R^2$ & FWHM$_{\\text{TOF}}$ & ');
    fprintf(fid, 'FWHM$_L$ & FWHM$_{\\text{TOF}}^{\\text{geom}}$ & frac$_{\\text{geom}}$ & $N$ \\\\\n');
    fprintf(fid, '\\hline\n');
    for i = 1:height(Summary)
        fprintf(fid, '%s & %.3e & %.3e & %.3f & %.3f & %.3e & %.3e & %.3e & %.3f & %d \\\\\n', ...
            char(Summary.Scenario(i)), ...
            Summary.slope(i), ...
            Summary.intercept(i), ...
            Summary.R(i), ...
            Summary.R2(i), ...
            Summary.FWHM_TOF(i), ...
            Summary.FWHM_L(i), ...
            Summary.FWHM_TOF_geom(i), ...
            Summary.geom_fraction(i), ...
            Summary.N_used(i));
    end
    fprintf(fid, '\\end{tabular}\n');
    fprintf(fid, '\\caption{Riepilogo correlazione TOF–path per gli elettroni.}\n');
    fprintf(fid, '\\label{tab:electron_tof_path}\n');
    fprintf(fid, '\\end{table}\n');
    fclose(fid);
    fprintf('    -> Tabella LaTeX in: %s\n', texFile);
end

fprintf('>>> Analisi electron TOF completata.\n');