function texFile = beamSeparationToLatex(stats, varargin)
% BEAMSEPARATIONTOLATEX  Esporta le S di separazione in una tabella LaTeX.
%
%   texFile = simion.beamSeparationToLatex(stats)
%   texFile = simion.beamSeparationToLatex(stats, 'Dimension', 'y', ...
%                                          'Filename', 'sep_y.tex')
%
% INPUT
%   stats : struct restituito da simion.computeBeamStatsInOut
%
% Name-Value:
%   'Dimension' : 'y' oppure 'r'  (default: 'y')
%   'Filename'  : nome file .tex da scrivere
%                 (default: 'beam_separation_y.tex' o '_r.tex')
%
% OUTPUT
%   texFile : path del file .tex creato

    p = inputParser;
    p.FunctionName = 'beamSeparationToLatex';

    addRequired(p, 'stats', @(s) isstruct(s));
    addParameter(p, 'Dimension', 'y', ...
        @(d) ischar(d) || isstring(d));
    addParameter(p, 'Filename', '', ...
        @(s) ischar(s) || isstring(s));

    parse(p, stats, varargin{:});

    dim = lower(char(p.Results.Dimension));

    switch dim
        case 'y'
            if ~isfield(stats, 'SeparationY')
                error('beamSeparationToLatex:NoSeparationY', ...
                      'Il campo stats.SeparationY non esiste.');
            end
            Tsep     = stats.SeparationY;
            ScolName = 'S_y';
            Slabel   = '$S_y$';
            defaultName = 'beam_separation_y.tex';

        case 'r'
            if ~isfield(stats, 'SeparationR')
                error('beamSeparationToLatex:NoSeparationR', ...
                      'Il campo stats.SeparationR non esiste.');
            end
            Tsep     = stats.SeparationR;
            ScolName = 'S_r';
            Slabel   = '$S_r$';
            defaultName = 'beam_separation_r.tex';

        otherwise
            error('beamSeparationToLatex:BadDimension', ...
                  'Dimension deve essere ''y'' oppure ''r''.');
    end

    % Filename effettivo
    if isempty(p.Results.Filename)
        filename = defaultName;
    else
        filename = char(p.Results.Filename);
    end

    % Controllo colonne minime
    requiredCols = {'Species1','Species2',ScolName};
    missing = setdiff(requiredCols, Tsep.Properties.VariableNames);
    if ~isempty(missing)
        error('beamSeparationToLatex:MissingColumns', ...
              'Colonne mancanti nella tabella di separazione: %s', ...
              strjoin(missing, ', '));
    end

    % Scrittura LaTeX (semplice, indipendente da tableToLatex)
    fid = fopen(filename, 'w');
    if fid < 0
        error('beamSeparationToLatex:FileError', ...
              'Impossibile aprire il file %s per scrittura.', filename);
    end

    cleaner = onCleanup(@() fclose(fid));

    fprintf(fid, '%% Auto-generated by simion.beamSeparationToLatex\n');
    fprintf(fid, '\\begin{tabular}{lll}\n');
    fprintf(fid, '\\toprule\n');
    fprintf(fid, 'Species 1 & Species 2 & %s\\\\\n', Slabel);
    fprintf(fid, '\\midrule\n');

    for i = 1:height(Tsep)
        s1 = string(Tsep.Species1(i));
        s2 = string(Tsep.Species2(i));
        S  = Tsep.(ScolName)(i);

        fprintf(fid, '%s & %s & %.3f\\\\\n', s1, s2, S);
    end

    fprintf(fid, '\\bottomrule\n');
    fprintf(fid, '\\end{tabular}\n');

    texFile = filename;
end